
SELECT C.NOME , C.EMAIL , E.ESTADO , T.NUMERO 
FROM CLIENTE C
INNER JOIN ENDERECO E
    ON E.ID_CLIENTE = C.IDCLIENTE
INNER JOIN TELEFONE T
    ON C.IDCLIENTE = T.ID_CLIENTE

-- utilizando IFNULL()

SELECT C.NOME, 
       IFNULL(C.EMAIL,'**********') AS 'EMAIL', 
       E.ESTADO, 
       T.NUMERO 
FROM CLIENTE C
INNER JOIN ENDERECO E
    ON E.ID_CLIENTE = C.IDCLIENTE
INNER JOIN TELEFONE T
    ON C.IDCLIENTE = T.ID_CLIENTE;

CREATE VIEW RELATORIO AS 
    SELECT C.NOME,
        C.SEXO ,
        C.EMAIL,
        T.TIPO,
        T.NUMERO,
        E.BAIRRO,
        E.CIDADE,
        E.ESTADO
    FROM CLIENTE C
    INNER JOIN TELEFONE T
        ON T.ID_CLIENTE = C.IDCLIENTE
    INNER JOIN ENDERECO E
        ON E.ID_CLIENTE = C.IDCLIENTE;

















