/* Entrando com mais telefones*/


UPDATE CLIENTE 
SET TELEFONE = '978654334'
WHERE NOME = 'CLARA';

/* Dois telefones par um usuario*/

UPDATE CLIENTE 
SET TELEFONE = '978654334 - 2941274271'
WHERE NOME = 'CLARA';

SELECT ENDERECO , COUNT(*) FROM CLIENTE GROUP BY ENDERECO;

-- saber quantidade de homens e mulheres


SELECT SEXO , COUNT(*) FROM CLIENTE ;

-- PRIMEIRA FORMA NORMAL 

-- 1 | TODO CAMPO VETORIZADO SE TORNARA OUTRA TABELA 
-- 2 | TODO CAMPO MULTIVALORADO SE TORNARA OUTRA TABELA. ( QUANDO O CAMPO FOR DIVISIVEL ) (ENDEREÇO)
-- 3 | TODA TABELA NECESSITA DE PELO MENOS UM CAMPO QUE IDENTIFIQUE TODO O REGISTRO COMO SENDO UNICO PRIMARY KEY


CREATE DATABASE COMERCIO;

USE COMERCIO

CREATE TABLE CLIENTE(
    IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    SEXO ENUM('M','F') NOT NULL,
    EMAIL VARCHAR(50) UNIQUE,
    CPF VARCHAR(15) UNIQUE
);

CREATE TABLE ENDERECO(
    IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
    RUA VARCHAR(30) NOT NULL,
    BAIRRO VARCHAR(30) NOT NULL,
    CIDADE VARCHAR(30) NOT NULL,
    ESTADO CHAR(2) NOT NULL,
    ID_CLIENTE INT UNIQUE,
    FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE) 
);

CREATE TABLE TELEFONE(
    IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO ENUM('RES','COM','CEL') NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    ID_CLIENTE INT,
    FOREIGN KEY(ID_CLIENTE)
    REFERENCES CLIENTE(IDCLIENTE)
);

-- endereço obrigatorio e cadastro de somente 1 
-- telefone não obrigatorio e cadastro de mais de 1 

-- RELACIONAMENTO 1 X 1 A CHAVE ESTRANGEIRA FICA NA TABELA MAIS FRACA
-- 

INSERT INTO CLIENTE VALUES(NULL,'JOAO','M','JOAO@IG.COM','1232134987');
INSERT INTO CLIENTE VALUES(NULL,'MARIA','F',NULL,'1231134977');
INSERT INTO CLIENTE VALUES(NULL,'JORGE','M','JORGE@IG.COM','2231134977');
INSERT INTO CLIENTE VALUES(NULL,'CELIA','F','CELIA@IG.COM','3231134977');
INSERT INTO CLIENTE VALUES(NULL,'CLARA','F','CLARA@IG.COM','5213214211');
INSERT INTO CLIENTE VALUES(NULL,'CLAUDIO','M','CLAUDIO@IG.COM','4113214211');


/*
+-----------+-------+------+--------------+------------+
| IDCLIENTE | NOME  | SEXO | EMAIL        | CPF        |
+-----------+-------+------+--------------+------------+
|         1 | JOAO  | M    | JOAO@IG.COM  | 1232134987 |
|         2 | MARIA | F    | NULL         | 1231134977 |
|         3 | JORGE | M    | JORGE@IG.COM | 2231134977 |
|         4 | CELIA | F    | CELIA@IG.COM | 3231134977 |
+-----------+-------+------+--------------+------------+
*/

INSERT INTO ENDERECO VALUES(NULL,'RUA ANTONIO SA','CENTRO','BELO HORIZONTE','MG',4);
INSERT INTO ENDERECO VALUES(NULL,'RUA CAPITAO HERMES','CENTRO','RIO DE JANEIRO','RJ',3);
INSERT INTO ENDERECO VALUES(NULL,'RUA GETULIO VARGAS','JARDINS','SAO PAULO','SP',2);
INSERT INTO ENDERECO VALUES(NULL,'RUA URUGUAIANA','ESTACIO','RIO DE JANEIRO','RJ',1);
INSERT INTO ENDERECO VALUES(NULL,'RUA DO OUVIDOR','CENTRO','VITORIA','ES',5);
INSERT INTO ENDERECO VALUES(NULL,'RUA DO IMPERADOR','CENTRO','RECIFE','PE',6);

/*
+------------+--------------------+---------+----------------+--------+------------+
| IDENDERECO | RUA                | BAIRRO  | CIDADE         | ESTADO | ID_CLIENTE |
+------------+--------------------+---------+----------------+--------+------------+
|          1 | RUA ANTONIO SA     | CENTRO  | BELO HORIZONTE | MG     |          4 |
|          2 | RUA CAPITAO HERMES | CENTRO  | RIO DE JANEIRO | RJ     |          3 |
|          3 | RUA GETULIO VARGAS | JARDINS | SAO PAULO      | SP     |          2 |
|          4 | RUA URUGUAIANA     | ESTACIO | RIO DE JANEIRO | RJ     |          1 |
+------------+--------------------+---------+----------------+--------+------------+
*/

-- TENTANDO ENTRAR COM ENTRADA DUPLICADA ( IMPOSSIVEL PORQUE ENDEREÇO É (1,1) )
INSERT INTO ENDERECO VALUES(NULL,'RUA URUGUAIANA DOIS','ESTACIO DOIS','RIO DE JANEIRO','RJ',1);

-- TABELA TELEFONE

INSERT INTO TELEFONE VALUES(NULL,'CEL','783272483',5);
INSERT INTO TELEFONE VALUES(NULL,'RES','483272483',4);
INSERT INTO TELEFONE VALUES(NULL,'CEL','383272483',3);
INSERT INTO TELEFONE VALUES(NULL,'RES','283272483',2);
INSERT INTO TELEFONE VALUES(NULL,'COM','183272483',1);
INSERT INTO TELEFONE VALUES(NULL,'COM','553272483',5);














