
-- SELEÇÃO -> É UM SUBCONJUNTO DO CONJUNTO TOTAL DE REGISTROS DE UMA TABELA

SELECT NOME,EXO,EMAIL /* PROJEOCAO */
FROM CLIENTE /* ORIGEM */
WHERE SEXO = 'F' /* SELECAO */

-- FUNÇÃO JOIN ---------------------------

SELECT NOME , EMAIL , IDCLIENTE 
FROM CLIENTE;

SELECT ID_CLIENTE , BAIRRO , CIDADE
FROM ENDERECO;

/* 
+---------+----------------+-----------+
| NOME    | EMAIL          | IDCLIENTE |
+---------+----------------+-----------+
| JOAO    | JOAO@IG.COM    |         1 |
| MARIA   | NULL           |         2 |
| JORGE   | JORGE@IG.COM   |         3 |
| CELIA   | CELIA@IG.COM   |         4 |
| CLARA   | CLARA@IG.COM   |         5 |
| CLAUDIO | CLAUDIO@IG.COM |         6 |
+---------+----------------+-----------+
 
+------------+---------+----------------+
| ID_CLIENTE | BAIRRO  | CIDADE         |
+------------+---------+----------------+
|          4 | CENTRO  | BELO HORIZONTE |
|          3 | CENTRO  | RIO DE JANEIRO |
|          2 | JARDINS | SAO PAULO      |
|          1 | ESTACIO | RIO DE JANEIRO |
|          5 | CENTRO  | VITORIA        |
|          6 | CENTRO  | RECIFE         |
+------------+---------+----------------+
*/

-- NOME , SEXO , BAIRRO , CIDADE 

-- MANEIRA INADEQUADA , PORÉM FUNCIONAL ==
SELECT NOME , SEXO , BAIRRO ,CIDADE 
FROM CLIENTE , ENDERECO
WHERE IDCLIENTE = ID_CLIENTE;

-- ======MANEIRA=ADEQUADA=================
SELECT NOME,SEXO,BAIRRO,CIDADE -- PROJEÇÃO
FROM CLIENTE -- ORIGEM
    INNER JOIN ENDERECO -- JUNÇÃO
    ON IDCLIENTE = ID_CLIENTE
WHERE SEXO = 'F'; -- SELEÇÃO

-- NOME , SEXO , EMAIL,TIPO,NUMERO
SELECT NOME,SEXO,EMAIL,TIPO,NUMERO
FROM CLIENTE
INNER JOIN TELEFONE
    ON IDCLIENTE = ID_CLIENTE;


-- NOME , SEXO , BAIRRO , CIDADE , TIPO , NUMERO

SELECT CLIENTE.NOME,CLIENTE.SEXO,ENDERECO.BAIRRO,ENDERECO.CIDADE,TELEFONE.TIPO,TELEFONE.NUMERO
FROM CLIENTE
INNER JOIN ENDERECO
    ON CLIENTE.IDCLIENTE=ENDERECO.ID_CLIENTE
INNER JOIN TELEFONE
    ON CLIENTE.IDCLIENTE=TELEFONE.ID_CLIENTE;

/*
+-------+------+---------+----------------+------+-----------+
| NOME  | SEXO | BAIRRO  | CIDADE         | TIPO | NUMERO    |
+-------+------+---------+----------------+------+-----------+
| JOAO  | M    | ESTACIO | RIO DE JANEIRO | COM  | 183272483 |
| MARIA | F    | JARDINS | SAO PAULO      | RES  | 283272483 |
| JORGE | M    | CENTRO  | RIO DE JANEIRO | CEL  | 383272483 |
| CELIA | F    | CENTRO  | BELO HORIZONTE | RES  | 483272483 |
| CLARA | F    | CENTRO  | VITORIA        | CEL  | 783272483 |
| CLARA | F    | CENTRO  | VITORIA        | COM  | 553272483 |
+-------+------+---------+----------------+------+-----------+
*/
--=======================================================
-- PONTEIRAMENTO ========================================
SELECT C.NOME,C.SEXO,E.BAIRRO,E.CIDADE,T.TIPO,T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
    ON C.IDCLIENTE=E.ID_CLIENTE
INNER JOIN TELEFONE T
    ON C.IDCLIENTE=T.ID_CLIENTE;

/* 
    DML -> DATA MANIPULATION LANGUAGE    ( INSERT , FILTER , UPDATE , DELETE  )
    DDL -> DATA DEFINITION LANGUAGE       
    DCL -> DATA CONTROL LANGUAGE
    TCL -> TRANSACTION CONTROL LANGUAGE
*/

-- FILTER

SELECT * FROM CLIENTE 
WHERE SEXO = 'M';

-- UPDATE 

SELECT * FROM CLIENTE
WHERE IDCLIENTE = 7;

UPDATE CLIENTE
SET SEXO = 'F'
WHERE IDCLIENTE = 7;

-- DELETE

SELECT * FROM CLIENTE 
WHERE IDCLIENTE = 8;

DELETE FROM CLIENTE 
WHERE IDCLIENTE = 8;

-- DDL

CREATE TABLE PRODUTO (
    IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_PRODUTO VARCHAR(30) NOT NULL,
    PRECO INT,
    FRETE FLOAT(10,2) NOT NULL
);

-- ALTER TABLE

-- ALTERANDO O NOME DE UMA COLUNA / CHANGE

ALTER TABLE PRODUTO 
CHANGE PRECO VALOR_UNITARIO INT NOT NULL;

ALTER TABLE PRODUTO 
CHANGE VALOR_UNITARIO VALOR_UNITARIO INT;

-- MODIFY - ALTERANDO O TIPO

ALTER TABLE PRODUTO 
MODIFY VALOR_UNITARIO VARCHAR(50) NOT NULL;


-- ADICIONANDO COLUNAS

ALTER TABLE PRODUTO 
ADD PESO FLOAT(10,2) NOT NULL;

-- APAGANDO UMA COLUNA

ALTER TABLE PRODUTO
DROP COLUMN PESO;

-- ADICIONANDO UMA COLUNA NA ORDEM ESPECIFICA

ALTER TABLE PRODUTO
ADD COLUMN PESO FLOAT(10,2) NOT NULL
AFTER NOME_PRODUTO;

-- CRIANDO UMA COLUNA E COLOCANDO ELA COMO A PRIMEIRA DA TABELA

ALTER TABLE PRODUTO 
ADD PESO FLOAT(10,2) NOT NULL
FIRST;

























