INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('LILIAN','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - 
RJ' , '947785696',887774856);


INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('CLARA','F','SENADOR SOARES - CENTRO - RIO DE JANEIRO - 
RJ' , '947785396',887734856);

SELECT NOW() AS DATA_HORA , 'CLARA LILIAN' AS PROFESSOR;

SELECT NOME,SEXO,EMAIL FROM CLIENTE;

SELECT NOME,SEXO,ENDERECO,EMAIL FROM CLIENTE();

SELECT * FROM CLIENTE;

SELECT * FROM CLIENTE WHERE NOME ='LILIAN';


# RETORNA VAZIO 

SELECT NOME,SEXO FROM CLIENTE WHERE ENDERECO LIKE 'RJ';

/* ENDEREÇO QUE TERMINE COM 'RJ' */

SELECT NOME,SEXO FROM CLIENTE WHERE ENDERECO LIKE '%RJ';

/* ENDEREÇO QUE COMECE COM 'RJ' */

SELECT NOME,SEXO FROM CLIENTE WHERE ENDERECO LIKE 'RJ%';

# ENDEREÇO QUE TEM 'CENTRO' NO MEIO

SELECT NOME,SEXO FROM CLIENTE WHERE ENDERECO LIKE '%CENTRO%';








